apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cerebro
  name: cerebro-gui-test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: cerebro
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cerebro
    spec:
      containers:
      - image: lmenezes/cerebro:0.9.4
        #args: ["-Dconfig.file=/etc/cerebro/application.conf"]
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: cerebro
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        volumeMounts:
        - name: db
          mountPath: /var/db/cerebro   
        - name: config
          mountPath: /etc/cerebro     
        - name: logs
          mountPath: /opt/cerebro/logs/    
        - name: tmp
          mountPath: /tmp    
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 1Gi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      terminationGracePeriodSeconds: 30
      volumes:
      - name: db
        emptyDir: {}       
      - name: logs
        emptyDir: {}    
      - name: tmp
        emptyDir: {}
      - name: config  
        emptyDir: {}

--- 

apiVersion: v1
kind: Service
metadata:
  labels:
    app: cerebro
  name: cerebro-gui-test 
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9000
  selector:
    app: cerebro
  sessionAffinity: None
  type: NodePort
        